webpack-contrib/css-loader

lib/compile-exports.js, test/camelCaseTest.js
See https://github.com/webpack/css-loader/pull/149#issuecomment-150118653
=> Extend camelcase option to support 'dashes' value

lib/loader.js, lib/localsLoader.js
I'd love to get this merged in ASAP. This bug causes issues currently with server-side rendering.
=> Fix errors due to missing semicolon

package.json
=> Add support for global class composition & compose-with (fixes #176)

README.md
Just spotted this light grammatical error and thought I would resolve it.
Ended up changing the whole sentence as it didn't seem quite right, but please let me know if you think it is worse by... well... denying the pull 😉
=> Resolving grammatical issue in README.md file

README.md
Documentation fix
No
Yes
**Summary**
The default for minimize is `false`, so updated the `README`
No
=> README - fix default for minimize

.travis.yml, README.md, package.json, yarn.lock
Chore
**Summary**
- Add `standard-version` part of the `webpack-defaults` tool set for changelog generation
- Fix Coverage badge in Readme
- Fix Minimum NodeJS version ( 4.3 )
=> chore(release): add standard-version & scripts

README.md
=> docs(README): fix link

README.md
documentation improvement
This updates and hopefully improves the `importLoaders` section to get a better understanding of how the option works. See https://github.com/webpack-contrib/css-loader/issues/510.
No
=> Improve importLoaders section and example

lib/processCss.js, package.json, test/localTest.js, yarn.lock
bugfix, refactoring
yep
**Summary**
Ref https://github.com/webpack-contrib/css-loader/issues/541
=> fix: preserve leading underscore in class names

package.json
chore
not required
not required
**Summary**
Just update deps
No
=> chore(package): update `source-list-map v0.1.7...2.0.0` (`dependencies`)

lib/localsLoader.js
- Fixes #602 
> edited by @michael-ciniawsky (Formatting && Added Issue)
=> fix: pass resolver to `localsLoader` (`options.alias`)

README.md
=> docs(README): fix malformed emoji

README.md
Fixing typos in the README file.
Nope.
Yup!
**Summary**
I noticed a few typos while reading through the README and figured I could fix them quickly.
No.
Thank you for the good documentation that was already there! 👍
=> docs(readme): various typo fixes

lib/CssSyntaxError.js, lib/processCss.js, package-lock.json, package.json, test/importTest.js, test/simpleTest.js
refactoring
Exists tests
Not required
**Summary**
Avoid using `babel-code-frame`, `postcss` already use code frames for errors
No
Not required
=> refactor: avoid using `babel-code-frame`

lib/postcss-css-loader-parser.js, lib/processCss.js
refactoring
Exists tests
Not required
**Summary**
Move postcss value parser plugin to own file
No
Not required
=> refactor: move value parser plugin to own file

.github/CODEOWNERS, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/BUG.md, .github/ISSUE_TEMPLATE/DOCS.md, .github/ISSUE_TEMPLATE/FEATURE.md, .github/ISSUE_TEMPLATE/MODIFICATION.md, .github/ISSUE_TEMPLATE/SUPPORT.md, .github/PULL_REQUEST_TEMPLATE.md
refactoring
Exists
Not required
**Summary**
Update github templates
No
No
=> refactor: update github templates

package-lock.json, package.json, test/__snapshots__/loader.test.js.snap, test/fixtures/scss/source.scss, test/helpers.js, test/loader.test.js
Test compatibility with `sass-loader`
No
No
=> test: sass-loader

lib/loader.js, lib/plugins/postcss-icss-parser.js, lib/plugins/postcss-import-parser.js, lib/plugins/postcss-url-parser.js
Migrate on `message` api
No
No
=> refactor: migrate on message api for postcss-import-parser

src/options.json, test/__snapshots__/errors.test.js.snap, test/__snapshots__/modules-option.test.js.snap, test/errors.test.js, test/fixtures/modules/issue-286/dep.css, test/fixtures/modules/issue-286/source.css, test/helpers.js, test/modules-option.test.js
=> test: issue 286

test/__snapshots__/loader.test.js.snap, test/fixtures/basic.css
More tests
No
`css-selector-tokenizer` break some selectors when you use `modules`
=> test: css stuff

index.js
=> refactor: remove unused file

package.json
=> ci: fix commitlint

test/__snapshots__/modules-option.test.js.snap, test/fixtures/modules/tests-cases/animation/source.css
fixes #872
Deps already updated, just release patch version for trigger CI and updates
No
No
=> fix: inappropriate modification of animation keywords

.eslintrc.js, .prettierrc, package-lock.json, package.json, test/__snapshots__/sourceMap-option.test.js.snap
=> chore: update defaults

.gitattributes, .github/CONTRIBUTING.md, package-lock.json, package.json
update defaults + es check for runtime
No
No
=> chore(defaults): update

README.md, package-lock.json
Fixed incorrect property description
=> docs(readme): fix property description

src/index.js, src/plugins/postcss-url-parser.js, test/__snapshots__/modules-option.test.js.snap
refactor for future fixes
No
No
=> refactor: postcss plugins

src/index.js, test/__snapshots__/exportOnlyLocals-option.test.js.snap, test/__snapshots__/modules-option.test.js.snap, test/exportOnlyLocals-option.test.js, test/modules-option.test.js
=> refactor: code and tests

test/__snapshots__/exportOnlyLocals-option.test.js.snap, test/__snapshots__/modules-option.test.js.snap, test/fixtures/modules/composes.css
=> test: more

src/plugins/postcss-url-parser.js, test/__snapshots__/url-option.test.js.snap, test/fixtures/url/url.css, test/url-option.test.js
fix: hanling characters as URL escapes in url
No
No
=> fix: hanling characters as URL escapes in url

src/plugins/postcss-url-parser.js, src/utils.js
Simplify code and increase perf
No
No
=> Perf postcss url parser 1

src/index.js, src/plugins/postcss-icss-parser.js, src/plugins/postcss-import-parser.js, src/plugins/postcss-url-parser.js, src/utils.js, test/__snapshots__/localsConvention-option.test.js.snap, test/__snapshots__/modules-option.test.js.snap, test/helpers/getModuleSource.js
=> Refactor code 1

README.md, src/options.json, src/utils.js, test/__snapshots__/modules-option.test.js.snap, test/__snapshots__/validate-options.test.js.snap, test/fixtures/modules/issue-1063/global.css, test/fixtures/modules/issue-1063/issue-1063.js, test/fixtures/modules/issue-1063/local.css, test/modules-option.test.js, test/validate-options.test.js
=> feat: modules.mode callback function

src/utils.js, test/__snapshots__/localsConvention-option.test.js.snap, test/fixtures/modules/localsConvention/localsConvention.css
=> fix: don't generate an invalid code for `locals`

README.md, package-lock.json, package.json, src/index.js, src/plugins/postcss-icss-parser.js, src/plugins/postcss-import-parser.js, test/__snapshots__/import-option.test.js.snap, test/__snapshots__/modules-option.test.js.snap, test/__snapshots__/onlyLocals-option.test.js.snap, test/fixtures/import/unresolved.css, test/fixtures/import/unresolved.js, test/fixtures/modules/composes/composes-preprocessors.css, test/fixtures/modules/composes/composes.css, test/fixtures/modules/composes/sass-file.sass, test/fixtures/modules/issue-914/source.css, test/fixtures/modules/issue-914/source.js, test/fixtures/modules/node_modules/test/index.css, test/fixtures/modules/node_modules/test/package.json, test/fixtures/modules/unresolved/source.css, test/fixtures/modules/unresolved/source.js, test/helpers/getErrors.js, test/helpers/normalizeErrors.js, test/import-option.test.js, test/modules-option.test.js
=> Fixed resolve modules with and without tilde

src/plugins/postcss-url-parser.js, test/__snapshots__/import-option.test.js.snap, test/__snapshots__/sourceMap-option.test.js.snap, test/fixtures/import/import.css, test/helpers/normalizeErrors.js, test/sourceMap-option.test.js
=> test: coverange

.gitignore, src/utils.js, test/__snapshots__/import-option.test.js.snap, test/__snapshots__/modules-option.test.js.snap, test/__snapshots__/url-option.test.js.snap, test/fixtures/import/import-absolute.js, test/fixtures/modules/composes/composes-absolute.js, test/fixtures/url/url-absolute.js, test/import-option.test.js, test/modules-option.test.js, test/url-option.test.js
=> Feat support absolute path

src/index.js, src/plugins/postcss-import-parser.js, src/plugins/postcss-url-parser.js
=> fix: performance

src/plugins/postcss-url-parser.js
=> fix: remove unnecessary `console` call

README.md
update defaults on readme to v4 defaults
=> update options table in readme

src/utils.js, test/__snapshots__/loader.test.js.snap, test/__snapshots__/modules-option.test.js.snap, test/fixtures/modules/composes/composes-named.js, test/fixtures/modules/composes/composes.css, test/fixtures/modules/composes/top-relative.css, test/modules-option.test.js
fixes #1155
In theory yes, but previously behavior was wrong, we event list it in changelog, so I mark it as regression
Here also fix for `namedExport` and `exportOnlyLocals` (it was broken before)
=> Issue 1155

.gitignore, test/__snapshots__/import-option.test.js.snap, test/__snapshots__/url-option.test.js.snap, test/fixtures/import/import-file-protocol.js, test/fixtures/url/url-file-protocol.js, test/import-option.test.js, test/url-option.test.js
Add test for import with file protocol
No
No
=> Add test for import with file protocol

src/utils.js, test/__snapshots__/modules-option.test.js.snap, test/fixtures/modules/mode/icss/icss.js, test/fixtures/modules/mode/icss/relative.icss.css, test/fixtures/modules/mode/icss/vars.icss.css, test/fixtures/modules/mode/modules-2.js, test/fixtures/modules/mode/relative.modules.css, test/modules-option.test.js
Auto enable `icss` modules for all files for which `/\.icss\.\w+$/i.test(filename)` return `true`
No
No
=> Feat: auto enable icss modules

src/CssSyntaxError.js, test/__snapshots__/loader.test.js.snap, test/helpers/getErrors.js, test/helpers/normalizeErrors.js, test/loader.test.js
Adds the file path to the error message
No
No
=> Refactor: postcss error message

README.md
Just updating README example code to avoid people get ValidationError from copying those examples over.
=> docs: context is localIdentContext in README 

src/plugins/postcss-icss-parser.js, src/plugins/postcss-import-parser.js, src/plugins/postcss-url-parser.js, test/__snapshots__/loader.test.js.snap, test/loader.test.js
=> feat: postcss@8

test/__snapshots__/modules-option.test.js.snap, test/fixtures/modules/issue-1228/source.css, test/fixtures/modules/issue-1228/source.js, test/modules-option.test.js
fixes #1228
No
test to avoid regressions
=> test: animation properties

README.md
=> docs: fix outdated docs

package-lock.json, test/fixtures/url/url.css, test/helpers/getCompiler.js, test/url-option.test.js
=> test: filter root relative urls

README.md
=> docs: fix outdated docs(#1258)

package-lock.json, package.json, src/index.js, src/utils.js, test/__snapshots__/loader.test.js.snap, test/fixtures/index-loader-syntax-sass.css, test/fixtures/index-loader-syntax-sass.modules.css, test/fixtures/index-loader-syntax.css, test/fixtures/index-loader-syntax.js, test/fixtures/index-loader-syntax.modules.css, test/fixtures/my-inline-loader/index.js, test/helpers/getExecutedCode.js, test/loader.test.js
fixes #1270
No
More tests + update deps
=> Fix inline loader syntax in import

src/index.js, src/utils.js, test/__snapshots__/import-option.test.js.snap, test/fixtures/import/import.css, test/fixtures/import/my.scss
=> fix: handling `@import` with spaces and any extensions

README.md
Adds information about the supported version of the webpack to the documentation
No
No
=> docs: added supported webpack version

src/runtime/cssWithMappingToString.js, test/runtime/__snapshots__/api.test.js.snap, test/runtime/api.test.js, test/sourceMap-option.test.js
=> fix: issue 1322

test/url-option.test.js
=> Test: updated

package-lock.json, package.json, src/options.json, test/__snapshots__/modules-option.test.js.snap, test/__snapshots__/validate-options.test.js.snap
Add link, improve errors.
No
No
=> feat: add `link` in schema

test/__snapshots__/modules-option.test.js.snap, test/fixtures/url/url.css
added test for #1342
No
fixes #1342
=> test: added

README.md, src/index.js, src/options.json, src/utils.js, test/__snapshots__/modules-option.test.js.snap, test/__snapshots__/validate-options.test.js.snap, test/fixtures/modules/namedExport/template-2/index.css, test/fixtures/modules/namedExport/template-2/index.js, test/fixtures/modules/namedExport/template-2/template.js, test/modules-option.test.js, test/validate-options.test.js
=> feat: exportLocalsConvention option could be a function

CHANGELOG.md, README.md, src/options.json, src/utils.js, test/__snapshots__/exportType.test.js.snap, test/__snapshots__/validate-options.test.js.snap, test/exportType.test.js, test/fixtures/basic-string-css-modules.js, test/fixtures/basic-string.js, test/validate-options.test.js
deprecate `to-string-loader`, you don't need this anymore
No
No
=> Feat export type string

README.md
The old form does not make grammatical sense.
N/A
N/A
=> Reword sentence in README

README.md
This is quite a big PR. Adds proper types...
=> docs(readme): added types

src/cjs.js, src/utils.js
https://github.com/webpack-contrib/css-loader/issues/1422
=> export defaultGetLocalIdent

src/cjs.js
Great you suddenly decided to export `defaultGetLocalIdent` function, bad you did not actually exported it. This should fix it.
=> Fixes defaultGetLocalIdent export

README.md
Fixes https://github.com/webpack-contrib/css-loader/pull/1459
No
No
=> docs: update webpack v5 note in README

.cspell.json, .github/workflows/nodejs.yml, babel.config.js, package-lock.json, package.json
Update Nodejs
minimum supported Nodejs version is 14.15.0
Let's update dependencies separate.
=> build!: minimum supported Nodejs version is 14.15.0

package-lock.json, package.json, test/__snapshots__/modules-option.test.js.snap
update deps before release
No
No
=> chore(deps): update

package-lock.json, package.json, test/__snapshots__/esModule-option.test.js.snap, test/__snapshots__/exportType.test.js.snap, test/__snapshots__/import-option.test.js.snap, test/__snapshots__/loader.test.js.snap, test/__snapshots__/modules-option.test.js.snap, test/__snapshots__/sourceMap-option.test.js.snap, test/sourceMap-option.test.js
upgrade dependencies to the latest version
No
No
=> chore: upgrade dependencies to the latest version

package-lock.json
=> chore: deps update

package-lock.json, package.json, test/__snapshots__/modules-option.test.js.snap, test/fixtures/modules/nesting/css.css, test/fixtures/modules/nesting/css.js, test/fixtures/modules/scope/css.css, test/fixtures/modules/scope/css.js, test/modules-option.test.js
Support nesting CSS and `@scope` at-rule
No
No
=> test: css nesting

package.json
Fix https://github.com/webpack-contrib/css-loader/issues/1567
No
No
=> feat: add `@rspack/core` as an optional peer dependency

package-lock.json, package.json, test/__snapshots__/modules-option.test.js.snap, test/fixtures/modules/composes/global.css, test/fixtures/modules/composes/global.js, test/fixtures/modules/scope/css.css, test/modules-option.test.js
update deps and add tests + tests on global composes
No
No
=> fix: do not break `@scope` at-rule without params

.husky/commit-msg, .husky/pre-commit, package.json
=> chore: husky migration

CHANGELOG.md
=> docs: typescript migration

src/utils.js
https://github.com/webpack/webpack/pull/18779
No
No
=> fix: use official `hash*` options for hashes
