- README.md
I'm thinking we should standardise the casing as "CSS Module", although it's clearly up for debate.
> Use title case for CSS Module in readme

- lib/parseSource.js
- test/moduleTestCases/simple/expected.css
- test/moduleTestCases/simple/source.css
This fixes the incorrect matching of floating point keyframe values as class names:
@keyframes z {
2.5% {color: green;}
}
Previously, the "5" in "2.5%" would be matched as a class name.  This commit fixes that.
> Improved class and ID regex selector match.

- lib/loader.js
- test/helpers.js
- test/sourceMapTest.js
> Ignore null source maps

- lib/processCss.js
- test/localTest.js
Class composition is broken with "non-word" (`\w`) characters due to the regex used to split tokens.
Perfectly valid classes such as `.my-class` or `.mycläss` are broken as they get split up.
This PR updates the regex to use `\S` instead of `\w`which allows these characters and thus fixes the problem. 
Additionally, a test has been added to verify composition works with a class that contains a hyphen (which fails without the updated regex).
> Fix broken composition with class names that contain characters other than [A-Za-z0-9_]

- package.json
There is a bug in the version of `postcss-normalize-urls` used by cssnano 1.4.2 which causes it to mess up data URIs (e.g. inline fonts and images) by converting `//` to `/`. Updating to the latest cssnano resolves this issue.
> Update cssnano to 2.1.0

- package.json
It fixes https://github.com/webpack/css-loader/issues/107
> Upgrade `postcss-modules-local-by-default`

- lib/getLocalIdent.js
I am setting `localIdentName=[name]の[local]` and was surprised that the `の` has been changed into a hyphen.
In CSS, any characters above U+00A0 are allowed, [per the specification](http://www.w3.org/TR/CSS21/syndata.html#characters) (emphasis mine):
> In CSS, _identifiers_ (including element names, classes, and IDs in [selectors](http://www.w3.org/TR/CSS21/selector.html)) can contain only the characters [a-zA-Z0-9] __and ISO 10646 characters U+00A0 and higher__, plus the hyphen (-) and the underscore (_) […]
> Allow ISO 10646 characters U+00A0 and higher in local ident

- lib/loader.js
- package.json
- test/camelCaseTest.js
This patch helps developers use `css-modules` with external libraries, like bootstrap. Popular css frameworks use *kebab-case* (bootstrap, foundation), or maybe other, like *snake_case*. We can resolve this problem if would automatically convert them to *camelCase*.
```css
/* styles.css */
.btn-info {
color: blue;
}
```
```js
// app.js
const styles = require('!css?modules&camelCase!./styles.css');
console.log(styles.btnInfo) // _38r5hlPyrqKLodJwWOdM1k
console.log(styles['btn-info']) // undefined
```
> Added camelCase option

- lib/processCss.js
- package.json
- test/moduleTestCases/values/expected.css
- test/moduleTestCases/values/source.css
- test/valuesTest.js
Currently some testcases are failing.
Relevant issues:
* css-modules/postcss-modules-values#1
* css-modules/postcss-modules-values#2
* css-modules/postcss-modules-values#3
cc @geelen @markdalgleish @joshwnj
> added CSS Modules values support

- lib/compile-exports.js
- lib/loader.js
- lib/localsLoader.js
Fixes https://github.com/webpack/css-loader/pull/149#issuecomment-150114155
> Added missing camelCase option for locals loader

- lib/processCss.js
- test/urlTest.js
This allows value like `-webkit-image-set(url('some-url.png') 1x, url('some-other-url.png') 2x)` to be parsed and transformed the by loader.
It fixes #200.
> Support for nested items

- README.md
Hi @sokra et al,
I was searching all around the internet trying to find a way to camelize the class names exported from css loader (in conjunction with css modules), when I found your commit adding the camelCase query. :clap: 
I was hoping to surface that information in the documentation.
> add documentation for camelCase query parameter

- package.json
Setting the minimum version of the node engine will make npm to warn or
complain, if node `engine-strict` config is set to true, whenever the
installation environment does not meet this requirement.
Background:
`css-loader` depends on `postcss` that uses native promises. Promises
where introduced in node version 0.12.0. So `css-loader`
*transitively inherits* this dependency.
Related to #144.
> Specify node engine minimum version

- package.json
https://github.com/webpack/css-loader/issues/133
> Fixes issue #133 with unicode strings

- lib/processCss.js
- package.json
- test/helpers.js
- test/simpleTest.js
I used babel-code-frame package formatting syntax errors code frames. That makes it consistent with Babel output which is I think very important as it makes it less cognitive efforts to recognize and process the error.
You can also see that there's no duplicated filename in error message as webpack already print module name.
Before:
After:
See also:
* https://github.com/babel/babel-loader/pull/287
* https://github.com/postcss/postcss-loader/pull/87
> Consistent format for syntax errors.

- lib/getLocalIdent.js
- test/localTest.js
According to the CSS spec, "identifiers cannot start with a digit, two hyphens, or a hyphen followed by a digit" ([Source](https://www.w3.org/TR/CSS2/syndata.html#value-def-identifier))
The current regular expression doesn't quite follow the spec, leading to unnecessary prefixing. I noticed this when using the `[emoji]` placeholder in `localIdentName`. Every emoji was being prefixed with an underscore, despite [Glen Maddern's site](https://glenmaddern.com/) proving to the world that a single emoji is a valid class name.
Also, I noticed that this prefixing behaviour was currently untested, so I've added some test cases for the new regular expression to show how it works in practice.
cc @geelen
> Prefix hashes with underscores based on CSS spec

- lib/processCss.js
> Disable Autoprefixer in cssnano

- README.md
Summary:
----
Webpack v2.1.0-beta.26 introduced a breaking change to require loaders to have the `-loader` suffix. 
This PR updates the README to show that pattern as an example instead of using the shorthand naming.
cc: @sokra @SpaceK33z
> Make -loader suffix consistent in README.md

- README.md
- lib/processCss.js
- test/customGetLocalIdentTest.js
> expose getLocalIdent

- lib/loader.js
- lib/localsLoader.js
- package.json
see: https://github.com/webpack/loader-utils/issues/56
> fix deprecation warning (loader-utils)

- lib/loader.js
- test/sourceMapTest.js
bugfix
Yes
Not relevant
**Summary**
Simplifies and correct sourcemaps generation by returning absolute sources paths and removing sourceRoot.
Fix #373 and #280
No
> use absolute paths and remove sourceRoot when generating sourcemaps

- lib/compile-exports.js
- test/camelCaseTest.js
- test/helpers.js
Bugfix, it makes sure that keys that are the same in different case styles (e.g. dashed, camelCase, dashedCamelCase) are not added to the resulting output when `?camelCase` is enabled.
E.g. a class name `.bla` would be `bla` as a default, but also `bla` in camelCase whereas `.my-bla` would yield `my-bla` and `myBla`. Currently the constructed document for the locals contains two entries, like this:
```json
{
"bla": "_1L-rnCOXCE_7H94L5XT4uB",
"bla": "_1L-rnCOXCE_7H94L5XT4uB",
}
```
if `camelCase` is enabled.
No, because the test helper uses JSON deserialization, which removes the dupe.
**Summary**
When using CSS modules with Typescript for example, you encounter something like this:
```
ERROR in …
```
> fix: do not export duplicate keys

- README.md
- lib/css-base.js
- package.json
- test/cssBaseTest.js
feature
yes
no
**Summary**
This feature is useful when you need to pass the result of css-loader to angular: call to require('to-string-loader!css-loader? sourceMap!sass-loader?sourceMap!./ test.scss') will include source mapping, And finally assigned to the component's styles metadata
I think no, Unless some code assumes that the css content does not have source maps
It's useful to angular component style.
> feat: Include the sourceMappingURL & sourceURL when toString()

- README.md
- lib/compile-exports.js
- test/camelCaseTest.js
feature/performance
yes
yes
**Summary**
* fixes #440 
* fixes #368 
No
> feat: allow removal of original class name

- lib/compile-exports.js
- test/camelCaseTest.js
bugfix
yes
n/a
**Summary**
When converting a class name without dashes, the newly introduced `'only'` and `'dashesOnly'` settings for the `camelCase` option would only ever add the class name to locals if it was different to the standard class name. Any class w/o dash would therefore not be added to the locals at all.
No
Introduced in #445 - released in `0.27.0`
> fix: incorrect handling of non-mutated class names

- lib/convert-source-map.js
- lib/css-base.js
- package.json
fixes #451 #450 , [source-map-loader #34](https://github.com/webpack-contrib/source-map-loader/issues/34)
> fix(lib): rm comment, rename const => var

- README.md
docs
n/a
yes
**Summary**
Added a hint from what version the new `dashesOnly` and `only` are available.
See #457
no
> Add minimum version to new camelCase options

- README.md
- lib/createResolver.js
- lib/loader.js
- test/aliasTest.js
Hi guys,
I found sometimes, it's not easy to change the source file / input file of css-loader, e.g.: when we're using sass files in another package (`bootstrap-sass`), we'll get a lot of complains about `Cannot resolve 'file' or 'directory' ...`. 
There are tons of questions on Google about this. 
For `bootstrap`, we may use `$icon-font-path` or `bootstrap-loader`, but for other projects, we have nothing.
`resolve-url-loader` is a solution, but it's based on source-map and makes the compilation much slower.
So what do you think if we rewrite urls in `css-loader`?
Here's an example to load `bootstrap-sass` with `sass-loader`, `css-loader` & `style-loader`
``` javascript
// webpack.config.js
// ## Webpack Configuration
var path = require('path');
module.exports = {
entry: "./src/entry", …
```
> Add alias feature to rewrite urls

- lib/processCss.js
bugfix
N/A
N/A
**Summary**
css-loader relies on cssnano, which relies on postcss-filter-plugins, which relies on uniqid, which relies on macaddress.
[macaddress](https://github.com/scravy/node-macaddress) has a global leak in v0.2.8.  They accidentally create a [global variable named `addresses`](https://github.com/scravy/node-macaddress/blob/0.2.8/index.js#L34).  This is a problem, because if you use this pacakge, and you supply `--check-leaks` to mocha, mocha will spaz out about the fact that there's this extra global variable.
The good news is, this is fixed in macaddress#master.  The bad news is, they haven't [published the fix for 9 …
> Only load cssnano if we're going to use it.

- lib/processCss.js
- test/moduleTestCases/urls/expected.css
- test/moduleTestCases/urls/source.css
- test/urlTest.js
Bugfix
yes
not required
**Summary**
Ref: https://github.com/webpack-contrib/css-loader/issues/410
no
not required
> fix: loader now correctly handles `url` with space(s) [#410].

- test/sourceMapTest.js
Tests
yes
not required
**Summary**
Ref: https://github.com/webpack-contrib/css-loader/issues/484
No
not required
> test: add tests when css contain data uri and source map enabled

- test/simpleTest.js
Tests
it is tests
not required
**Summary**
Ref: https://github.com/webpack-contrib/css-loader/issues/459
no
not required
> test: add test with escaped characters

- lib/css-base.js
- test/cssBaseTest.js
bugfix
yes
not required
**Summary**
https://github.com/webpack-contrib/css-loader/issues/454
no
not required
> fix: use `btoa` instead `Buffer`

- lib/processCss.js
- test/urlTest.js
Bugfix
yes
not required
**Summary**
Ref https://github.com/webpack-contrib/css-loader/issues/237
No
Not required
> fix: url with trailing space(s) is now handled correctly

- test/simpleTest.js
tests
it is tests
not required
**Summary**
Close https://github.com/webpack-contrib/css-loader/issues/211
no
not required
> Tests: add test with `charset` directive [#211].

- lib/processCss.js
- package.json
- test/valuesTest.js
bugfix, imho it is critical bugfix
ues
not required
**Summary**
Ref: https://github.com/webpack-contrib/css-loader/issues/424
no
not required
> fix: imported variables are replaced in exports if followed by a comma

- README.md
just typo in read :smile: 
not required
not required
**Summary**
not required
no
not required
> docs(README): fix typo in maintainers link

- lib/processCss.js
Chore
not required
not required
**Summary**
Move comment on right place and fix typo
not required
> chore: update comment

- lib/processCss.js
- test/importTest.js
bugfix
yes
not required
**Summary**
`import` directive is case insensitive. Spec https://www.w3.org/TR/CSS22/syndata.html#characters :smile: 
no
not required
> fix: case insensitivity of @import

- README.md
Gosh, I spent so much time understanding why I was able to compose a class with an internal class but not an external class in my css moduled style files.
I wanted to disable "import" because I didn't want that people use "@import" in the css files and wanted them make it importing via javascript like this:
```javascript
import '~/styles/index.css'
import styles from './index.css'
```
*BUT* disabling "import" option makes unavailable the fact to import external class in css-modules `composes` feature.
😒😒😒😒
> docs(README): update import section

- README.md
- Mistake about emoji
- Italic is probably better than quote
> docs(README): update warning note about import

- README.md
Recently needed this and I think it’s worth documenting for other folks. Took me a few days to figure out.
The difference between to-string-loader and extract-loader is that former wraps the CSS in a JS module while latter executes the css-loader’s output at compile time and passes that to the next loader in the chain. Came in handy when we needed some further post processing.
> docs(README): add extract-loader example

- lib/loader.js
- lib/processCss.js
- test/sourceMapTest.js
bugfix
not required
not required
**Summary**
https://github.com/webpack-contrib/sass-loader/issues/296#issuecomment-288464857
No
> perf: generate source maps only when explicitly set

- lib/processCss.js
- test/urlTest.js
bugfix
yes
not required
**Summary**
Ref: https://github.com/webpack-contrib/css-loader/issues/236
no
not required
> fix: allow to specify a full hostname as root URL

- lib/processCss.js
- test/importTest.js
- test/urlTest.js
bugfix
yes
not required
**Summary**
Ref: https://github.com/webpack-contrib/css-loader/issues/463
not required
> fix: don't handle empty @import and url()

- lib/loader.js
- lib/processCss.js
- test/sourceMapTest.js
bugfix
yes
**Summary**
https://github.com/webpack-contrib/css-loader/issues/529
No.
We need more tests and good review on this.
> fix: source maps path on `windows`

- lib/processCss.js
> fix: correct plugin order for CSS Modules

- lib/compile-exports.js
- test/camelCaseTest.js
Regex tweak for matching dashes in class names.
No
**Summary**
I was running into the same issue as https://github.com/webpack-contrib/css-loader/issues/244 whereby classes with double dashes in it still had one dash left even though I have camelCase set to 'dashes'. All I've done is change the regex to match one or more dashes and remove them all. 
Not to my knowledge, all tests pass.
> fix: match mutliple dashes (`options.camelCase`)

- test/simpleTest.js
tests
not required
not required
**Summary**
Related issue https://github.com/webpack-contrib/css-loader/issues/578
no
not required
> test: add test for escaped selector

- lib/processCss.js
- test/importTest.js
I accidentally found this issue when using size-limit on an exported library where we kept the import-normalize from https://www.npmjs.com/package/postcss-normalize inside the exported library.
Issue is that Webpack currently throws on the simple statement as it tries to parse it as a normal import.
To fix I added the failing test first, then fixed the regexp which matches the import statements and made the url handling generally more tolerant.
> fix: stricter `@import` tolerance

- lib/loader.js
- lib/processCss.js
- test/aliasTest.js
Improvement in alias handling
Of course
**Summary**
Hi :)
Thank you for this great webpack loader. Actually, we are using it a lot into [nuxt.js](https://github.com/nuxt/nuxt.js).
We have an issue with the css-loader used into the vue files, we have a global webpack alias named `~` and it's used a lot to require file this way: `import '~/assets/my-file.vue'`
Actually, we are using `css-loader` with this configuration:
```js
{
loader: 'css-loader',
options: {
minimize: true,
importLoaders: 1,
sourceMap: true,
alias: {
'/static': join(this.options.srcDir, 'static'),
'/assets': join(this.options.srcDir, 'assets')
}
}
}
```
So our users can do this into their CSS:
```css
.logo {
background: …
```
> fix: add support for aliases starting with `/` (`options.alias`)

- README.md
Fixes:
README fix
No code changes, just markdown fix. Here's the test:
------------------------------------------
**Before:**
`css-loader`'s `alias` follows the same syntax as webpack's `resolve.alias`, you can see the details at the [resolve docs] (https://webpack.js.org/configuration/resolve/#resolve-alias)
**After:**
`css-loader`'s `alias` follows the same syntax as webpack's `resolve.alias`, you can see the details at the [resolve docs](https://webpack.js.org/configuration/resolve/#resolve-alias)
------------------------------------------
Yes, made a super minor fix to it
**Motivation**
Saw an incorrectly formatted link, wanted to fix it
**Does this PR …
> docs(README): fix malformed link (`options.alias`)

- README.md
Docs.
No
**Summary**
Just improving docs.
No
> docs(README): add anchor tags to options table

- test/localsTest.js
A regression test follow up to this fix https://github.com/webpack-contrib/css-loader/pull/601
Feel free to ignore/close if it doesn't adhere to your normal test procedures.
> test: add case for `url` processing

- test/helpers.js
Fixes https://github.com/webpack-contrib/css-loader/issues/598
> Edited by @michael-ciniawsky (Formatting)
> test: removed redundant `modules` argument

- README.md
This is just a small update to the README. I've spent some time trying to understand how to properly configure the `importLoaders` option, and it seems like this number should always be the number of loaders that precede the the `css-loader`. If my understanding is correct, it would make sense to update this example. Otherwise, I think we should add some more documentation here to describe how to choose this number. I would be happy to update this PR with that documentation if someone could give me some more context on what's expected here. Thanks!
> Update importLoaders documentation

- lib/loader.js
bugfix
not required
not required
**Summary**
When `sourceMap` not specify we get `exports = module.exports = require("../node_modules/css-loader/lib/css-base.js")(undefined);` here https://github.com/webpack-contrib/css-loader/blob/master/lib/loader.js#L132
No
> fix(loader): correctly check if source map is `undefined`

- lib/escape-url.js
- lib/loader.js
- lib/processCss.js
- lib/url/escape.js
- test/helpers.js
- test/moduleTestCases/urls/expected.css
- test/urlTest.js
Bugfix
Yes. 2 existing tests changed to account for new behaviour (no single-quotes), 6 new tests of escaping.
I don't believe it's relevant. Unless just to document the quoting behaviour.
**Summary**
Fixes #615. Previously, modules had their quotes stripped unless the module-path contained a space. Now, quotes are always stripped and the URL returned from the module is escaped and wrapped in double-quotes if necessary. Modules returning a quote-wrapped string will have their own wrapping-quotes stripped before wrapping/escaping.
I don't think it does, modules wrapping in quotes like svg-url-loader should still …
> fix: proper URL escaping and wrapping (`url()`)

- lib/url/escape.js
- test/helpers.js
- test/urlTest.js
Closes #659
Test added for dependency exporting an empty object and null.
Not relevant
**Summary**
https://github.com/webpack-contrib/css-loader/pull/627 introduced an assumption about all dependencies exporting strings. To avoid including font-files, some users use `null-loader`, which effectively exports an empty object.
This PR checks for non-strings, restoring previous functionality for all non-string dependencies.
While this PR would enable previous usage patterns, I hope someone can come up with a better solution. The users are relying on `url([object Object])` being invalid CSS to avoid making requests for font files. This seems fragile in the long …
> fix: ignore invalid URLs (`url()`)

- test/urlTest.js
tests
yes
not matter
**Summary**
Ref: https://github.com/webpack-contrib/css-loader/issues/668
> test: hashes inside `@font-face` url

- lib/getLocalIdent.js
Bugfix.
No, because this project doesn't have e2e tests to test such case.
**Summary**
This PR fixes the behavior of `getLocalIdent`, which cause bugs with webpack 4.
[According to the chanelog](https://github.com/webpack/webpack/releases/tag/v4.0.0-beta.0), the `rootContext ` was added.  Loaders may use it to make stuff relative to the application root.
Also, `loaderContext.options` was removed, so the `options.context` is always value from `loaderContext.context`, which is actually filename without path.
So for example, if we have `a/a.css` and `b/a.css` both with `.c {}` content, the hash will be generated according to the `a.css` and `c` values (the same for these 2 independent files), which will …
> fix(getLocalIdent): add `rootContext` support (`webpack >= v4.0.0`)

- lib/processCss.js
- Fixes #697 
Removes the check for  'Module Mode'  (`local || global`) when resolving import URLs as it seems to be unneeded (?)
> fix(lib/processCss): don't check `mode` for `url` handling (`options.modules`)

- test/moduleMinimizeTestCases/custom-variables/expected.css
- test/moduleMinimizeTestCases/custom-variables/source.css
- test/simpleTest.js
tests
it is already tests
not required
**Summary**
Just add tests to ensure custom css variables works
no
> tests: css custom variables

- README.md
Updates README file so the `localIdentName` options are clearer and easier to access, added a link to it in the options, and moved it to its own section.
No, not relevant
Yes
**Summary**
It's currently not clear from the README what all the relevant options are for `localIdentName` and  it should have a link in the options table as to make access to it easier.
No
> docs(README): add more context to `localIdentName`

- lib/loader.js
- test/importTest.js
**What kind of change does this PR introduce?** 
Fixes #781
Yep
Nope 
**Summary**
This removes trailing whitespace from unquoted import urls
It shouldn't
> fix(loader): trim unquoted import urls

- .gitignore
- lib/compile-exports.js
- package-lock.json
- package.json
What:
update lodash to latest 4.17.11, switching away from deprecated lodash.xxx module
Why:
Remediate CVE-2018-3721 by upgrading lodash away from vulnerable and deprecated modules
> chore(package): switch from `lodash.camelcase` to `lodash` (`dependencies`)

- lib/css-base.js
- test/cssBaseTest.js
A bugfix
Yes, the contributed test fails without the change
Not required
**Summary**
Adds support for deduplication of string module ids, introduced with `optimization.namedModules` option in `webpack`. Fixes https://github.com/webpack-contrib/css-loader/issues/772
No
> Support deduplication of string module ids (optimization.namedModules)

- README.md
The syntax for importing a node module is not easy to find (see https://github.com/webpack/webpack/issues/1789#issuecomment-277024235). Maybe this will help a few people out.
Dcoumentation
> docs(readme): add an example how to `@import` a node module

- lib/loader.js
- test/urlTest.js
> fix: correctly processing url with `?#hash`

- lib/Warning.js
- lib/postcss-css-loader-parser.js
- lib/processCss.js
- test/__snapshots__/import-option.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/helpers.js
- test/import-option.test.js
BREAKING CHANGE: invalid `@import` at rules now emit warnings
Support `warning` from `postcss` also emit warnings on invalid `@import` at rules
Yes.
No
> fix: emit warnings on broken `@import`

- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
> test: ensure empty options are working

- lib/loader.js
- lib/localsLoader.js
- lib/processCss.js
Avoid passing unnecessary options
No
No
> refactor: code

- lib/utils.js
- test/__snapshots__/localIdentName-option.test.js.snap
- test/fixtures/modules/localIdentName.css
- test/localIdentName-option.test.js
- test/modules-option.test.js
More test for `localIdentName` option
No
No
> test: `localIdentName` option

- lib/plugins/postcss-import-parser.js
- test/__snapshots__/import-option.test.js.snap
`URL` can be in uppercase format in `@import` at rule
No
No
> fix: handle uppercase `URL` in `import` at-rules

- README.md
- lib/loader.js
- lib/plugins/postcss-icss-parser.js
- test/__snapshots__/import-option.test.js.snap
- test/fixtures/import/css-modules.css
- test/fixtures/import/values.css
- test/import-option.test.js
It is very misleading to disable `composes` using `import` option. Also based on search no one uses this feature. And i don't see any advantages for this.
Yes. `import` option only affect on `@import` at-rules and doesn't affect on `composes` declarations.
No
> feat: `import` option doesn't affect on `composes`

- lib/loader.js
- lib/localsLoader.js
- lib/utils.js
Move to utils for easy maintenance. 
No
No
> refactor: `importItemMatcher` util

- lib/loader.js
- lib/plugins/postcss-url-parser.js
Reduce url items for perf reason and refactor
No
No
> refactor: url replacer logic

- lib/utils.js
- test/__snapshots__/getLocalIdent-option.test.js.snap
- test/getLocalIdent-option.test.js
Drop compatibility `getLocalIdent` option with `webpack@2` and `webpack@3`
In theory - yes, but loader require `webpack@4` and it does not make sense so no
no
> refactor: drop getLocalIdent compatibility with webpack@2 and webpack@3

- lib/plugins/postcss-url-parser.js
- test/__snapshots__/url-option.test.js.snap
- test/url-option.test.js
For better DX we need emit warnings on invalid url.
No
No
> feat: emit warning on invalid url

- lib/loader.js
- lib/plugins/postcss-url-parser.js
- lib/utils.js
Use message api, also some improvement speed. 
no
no
> refactor: migrate on message api for url

- lib/loader.js
- lib/plugins/postcss-icss-parser.js
- test/__snapshots__/import-option.test.js.snap
- test/fixtures/import/css-modules.css
- test/fixtures/import/something.css
- test/fixtures/import/values.css
Full migration on message api
No
No
> refactor: migrate on message api for postcss-icss-plugin

- lib/loader.js
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
Increase perf, we avoiding double `css` parsing when developers use `postcss-loader`
No
No
> feat: reuse postcss ast from other loaders (i.e `postcss-loader`)

- README.md
- lib/loader.js
- test/__snapshots__/import-option.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/localIdentName-option.test.js.snap
- test/__snapshots__/modules-option.test.js.snap
- test/__snapshots__/url-option.test.js.snap
- test/fixtures/postcss-present-env/source.css
- test/fixtures/url/url.css
- test/getLocalIdent-option.test.js
- test/import-option.test.js
- test/modules-option.test.js
BREAKING CHANGE: by default css modules are disabled (now `modules: false` disable css modules), you can return old behaviour change this on `modules: 'global'`
Allow to disable css modules, some developers don't use `css` modules features and we decrease their perf.
Yes
No
> feat: allow to disable css modules and disable their by default

- README.md
- lib/loader.js
- lib/plugins/postcss-import-parser.js
- lib/plugins/postcss-url-parser.js
- test/__snapshots__/import-option.test.js.snap
- test/fixtures/import/alias.css
- test/fixtures/import/import.css
- test/fixtures/import/node_modules/package/tilde.css
- test/fixtures/import/relative.css
- test/fixtures/import/top-relative.css
- test/helpers.js
Refactor, some perf improvement.
No
No
> refactor: postcss plugins

- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/issue-636/foo.scss
- test/fixtures/modules/issue-636/source.scss
- test/helpers.js
- test/modules-option.test.js
Already fixed in master, just test.
fixes #636
> test: issue 636

- README.md
- src/index.js
- src/options.json
- src/utils.js
- test/__snapshots__/errors.test.js.snap
- test/__snapshots__/url-option.test.js.snap
- test/errors.test.js
- test/url-option.test.js
Allow to filter `url()`, fixes #779.
No
Supports only `Function` right now, if somebody want to use `RegExp` or `String` PR welcome, it is easy.
> feat: allow filtering urls

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/errors.test.js.snap
- test/__snapshots__/import-option.test.js.snap
- test/errors.test.js
- test/import-option.test.js
Allow to filter `import` at rules
No
No
> feat: allow to filter import at-rules

- src/options.json
- test/__snapshots__/errors.test.js.snap
- test/__snapshots__/getLocalIdent-option.test.js.snap
- test/errors.test.js
- test/getLocalIdent-option.test.js
> fix: `getLocalIdent` now accepts `false` value

- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/node_modules/@localpackage/color.css
- test/fixtures/modules/node_modules/@localpackage/style.css
- test/fixtures/modules/node_modules/@otherlocalpackage/style.css
- test/fixtures/modules/resolving-inside-node-modules.css
- test/modules-option.test.js
Just test to check `~` (#861) works as expected
No
No
> test: resolving in node_modules

- .circleci/config.yml
- .editorconfig
- appveyor.yml
- package-lock.json
- package.json
> chore(deps): update webpack-defaults

- README.md
Adding it to the documentation as a alternative / extended version of mini-css-extract. 
Extract css chunks offers hot module reloading while in development, allowing for good performance on the client and build. 
As you guys will know, mini-css is fast, this brings the benefits of it to development without losing the ability to hot reload.
None, just docs
With great respect, for you consideration.
> docs(readme): adding extract css chunks to REAMDME

- README.md
Wrong docs ;) It's correct in the list of options docs and also in code it's by default `false`.
None.
> docs: sourceMaps are disabled by default

- package-lock.json
- package.json
- src/utils.js
- test/__snapshots__/loader.test.js.snap
Fix escaping in selectors
fixes #578
No
/cc @jquense Looks like all tests good, except some selectors we need fix before merge
https://github.com/postcss/postcss-selector-parser/issues/174
https://github.com/postcss/postcss-selector-parser/issues/175
> fix: do not break selector with escaping

- README.md
> docs: improve documentation for `hashPrefix`, `context`, `getLocalIdent`

- package-lock.json
- package.json
- src/index.js
- test/__snapshots__/sourceMap-option.test.js.snap
- test/fixtures/source-map/basic.postcss.css
- test/fixtures/source-map/basic.scss
- test/helpers.js
- test/sourceMap-option.test.js
fixes #652
partial #886
No
Avoid prefix, because postcss generate invalid source map, also normalize path in source map from other loader (`node-sass` generate forward slash in source map, but it is invalid because source map using URLs, paths are invalid)
> fix: source map generation

- src/index.js
- test/camelCase-option.test.js
- test/errors.test.js
- test/getLocalIdent-option.test.js
- test/helpers.js
- test/icss.test.js
- test/import-option.test.js
- test/importLoaders-option.test.js
- test/loader.test.js
- test/localIdentName-option.test.js
- test/modules-option.test.js
- test/sourceMap-option.test.js
- test/url-option.test.js
use import instead `require`, also remove unused stuff after merge previous PR
No
No
> refactor: stuff

- src/index.js
Previously we stringify string, it is invalid. No test, because we already have test on this
No
No
> fix: sourcemap generating when previous loader pass sourcemap as string

- src/utils.js
fixes #906 
Use existing tests
No, it is more refactor than bugfix
No
> fix: avoid the "from" argument must be of type string error

- README.md
> fix: typo fix in scope section

- package.json
- src/utils.js
- test/__snapshots__/localIdentName-option.test.js.snap
- test/fixtures/modules/localIdentName.css
- test/localIdentName-option.test.js
Better export locals for escaping selectors
In theory yes becase it is change css output for classes and ids but previously implementation was wrong so it is bugfix
No
> refactor: better export escaped locals

- README.md
JPG and JPEG both stand for the Joint Photographic Experts Group image format, have the same meaning and are interchangeable.
> Update JPG regex example to match both formats

- .eslintignore
- babel.config.js
- src/runtime/api.js
- src/runtime/url-escape.js
- test/__snapshots__/loader.test.js.snap
use latest ES features for client code
No
No
> chore: use babel for client code

- src/index.js
- src/utils.js
> refactor: loader

- README.md
- src/utils.js
- test/import-option.test.js
- test/url-option.test.js
fixes #891
Yes
BREAKING CHANGE: you should return `true` when you want handle `url`/`@import` and return `false` if not
No
> fix: invert `Function` behavior for `url` and `import` options

- README.md
- package-lock.json
- package.json
- src/plugins/postcss-icss-parser.js
- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/composes.css
- test/fixtures/modules/something.css
- test/fixtures/modules/tests-cases/values-10/source.css
- test/fixtures/modules/values.css
Support `@value` at rule in selectors
Yes
BREAKING CHANGE: if you have name of `@value` in selector it will be replaced, you need to rename your name of `@value` or rename your selector
No
For next major release we need:
- fix `nothing` in test of css-loader
- fix problem when you use `@value test: 'something'` in selector
- refactor postcss-icss plugin
> feat: support `@value` at-rule in selectors

- package-lock.json
- package.json
- test/__snapshots__/loader.test.js.snap
- test/helpers.js
fix problem with some tests
No
No
> test: fix problem with nothing

- .github/CONTRIBUTING.md
- azure-pipelines.yml
- babel.config.js
- package-lock.json
- package.json
drop old node versions
Yes
BREAKING CHANGE: minimum required nodejs version is 8.9.0
No
> chore: minimum required nodejs version is 8.9.0

- package-lock.json
- package.json
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/modules-option.test.js.snap
- test/modules-option.test.js
With the suggested changes, `modules.getLocalIdent` would be allowed to return a falsy value, and in such case, the default `getLocalIdent` would be used instead.
I am setting up a new project with `webpack`, I wish to apply the same chain of loaders on different kinds of `.scss` files:
- `main.scss` specified as an `entry` in my configuration, meant to be used as global stylesheet
- `App.scss` SCSS modules which are imported from their matching component such as `App.js`
This setup works very well for me, except that `main.scss` classnames necessarily go through `css-loader` with `modules` enabled and using `localIdentName`.
See the following example:
```js
{
test: /\.scss$/,
loader: [
MiniCSSExtractPlugin.loader,
{
loader: 'css-loader',
options: {
importLoaders: 1, …
```
> feat: allow `modules.getLocalIdent` to return a falsy value

- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/modules-option.test.js
`loaderUtils.interpolateName` breaks if it passes `null` to path.relative
When css-loader 3.0.0 is used with `react-dev-utils/getCSSModuleLocalIdent` the build fails because getLocalIdent passes [`context` to `loaderUtils.interpolateName`](https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/getCSSModuleLocalIdent.js#L34). interpolateName then uses this `context` to [get a relative path using `path.relative()`](https://github.com/webpack/loader-utils/blob/master/lib/interpolateName.js#L71). While `undefined` (the value in ^2.1.1) is ... undefined and thus simply ignored by `path.relative()`, `null` is an object and causes the error below (shortened):
```
TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received …
```
> fix: default context should be undefined instead of null

- README.md
- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/path-placeholder.css
- test/modules-option.test.js
fixes #967 
Potentially yes, but it is big regression for `3.0.0` version so it is marked as bug.
No
> fix: converting reserved and control filesystem characters to `-`

- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/issue-966/button.css
- test/fixtures/modules/issue-966/toolbar.css
- test/modules-option.test.js
fixes #966
No
/cc @jquense looks all fine, can't see problems or bugs
> test: escaped in selector

- CHANGELOG.md
This specific line in the changelog comes from these two commits:
https://github.com/webpack-contrib/css-loader/pull/938
https://github.com/webpack-contrib/css-loader/pull/958
And it must be a typo to reference the old `camelCase` option as `exportLocalsStyle`
The release notes need to be updated, too https://github.com/webpack-contrib/css-loader/releases/tag/v3.0.0
> docs: fix `camelCase` reference in 3.0 changelog

- README.md
> docs: example with CSS modules and pure CSS

- src/runtime/getUrl.js
- test/__snapshots__/loader.test.js.snap
- test/runtime/__snapshots__/getUrl.test.js.snap
- test/runtime/api.test.js
- test/runtime/getUrl.test.js
no you can use `export default` for asset loader (fox example file-loader)
No
No
> feat: support es modules for assets loader

- README.md
> docs(readme): update default values for options

- src/runtime/getUrl.js
- test/__snapshots__/loader.test.js.snap
- test/runtime/__snapshots__/getUrl.test.js.snap
- test/runtime/getUrl.test.js
> fix: do not crash when an assert return `null` or `undefined`

- src/plugins/postcss-import-parser.js
- src/plugins/postcss-url-parser.js
- src/utils.js
- test/__snapshots__/import-option.test.js.snap
- test/fixtures/import/import.css
- test/fixtures/import/te'st.css
- test/fixtures/import/test test.css
fix: handling urls in @import
No
No
> fix: handling urls in @import

- src/runtime/api.js
- test/__snapshots__/import-option.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/fixtures/import/import.css
- test/fixtures/import/order-2.css
- test/fixtures/import/order-3-1.css
- test/fixtures/import/order-3.css
- test/fixtures/import/order-4-1.css
- test/fixtures/import/order-4-2-1.css
- test/fixtures/import/order-4-2-2.css
- test/fixtures/import/order-4-2.css
- test/fixtures/import/order-4.css
- test/fixtures/import/order.css
- test/runtime/__snapshots__/api.test.js.snap
logic was wrong with media and for order
Should be not, but feel free to open new issue if you have problem(s)
No
> fix: logic for order and media queries for imports

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/modules/issue-1033/issue-1033.js
- test/loader.test.js
> fix: don't output invalid es5 code when locals do not exists

- src/runtime/api.js
- test/runtime/__snapshots__/api.test.js.snap
- test/runtime/api.test.js
fixes #1034
No
https://github.com/mozilla/source-map/issues/340
sourceRoot is optional
> fix: do not output `undefined` when sourceRoot is unavailable

- README.md
- src/options.json
- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/fixtures/modules/exportGlobals-global/exportGlobals.css
- test/fixtures/modules/exportGlobals-global/exportGlobals.js
- test/fixtures/modules/exportGlobals-local/exportGlobals.css
- test/fixtures/modules/exportGlobals-local/exportGlobals.js
- test/fixtures/modules/exportGlobals-pure/exportGlobals.css
- test/fixtures/modules/exportGlobals-pure/exportGlobals.js
- test/fixtures/modules/issue-1063/issue-1063.js
- test/fixtures/modules/issue-1063/pure.css
- test/modules-option.test.js
- test/validate-options.test.js
> feat: the `exportGlobals` option for export global classes and ids

- src/options.json
I updated schema of `auto` field in `modules` to `regexp` instead of `object`.
> fix: update schema of auto in modules

- src/index.js
- test/__snapshots__/sourceMap-option.test.js.snap
- test/fixtures/source-map/with-query.css
- test/fixtures/source-map/with-query.js
- test/sourceMap-option.test.js
we don't need queries in sources
No
No
> fix: avoid query string in source maps

- .github/workflows/nodejs.yml
Webpack 5 does not support node 8 and its test case does not run in that environment. This causes CI to fail as css-loader tries to run the test suite in node 8.
This PR skips running the webpack 5 test suite in node 8 so that future PRs can be green, per https://github.com/webpack-contrib/css-loader/pull/1086#issuecomment-636926156.
n/a
n/a
> chore: don't test webpack 5 on node 8

- README.md
- src/options.json
- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/modules-option.test.js
- test/validate-options.test.js
The modules.auto feature as added in #1067 is pretty sweet. but sometimes you need more than a simple regex to check against your file path.
This PR allows `modules.auto` to be a function that that accepts the resourcePath and returns a boolean.
Along the way I tweaked some test case names to be a little clearer about what gets passed into modules.auto, which causes a bit of snapshot diff noise.
n/a
n/a
> feat: allow modules.auto to be a filter function

- .gitignore
- package-lock.json
- package.json
- src/index.js
- src/plugins/postcss-icss-parser.js
- src/plugins/postcss-import-parser.js
- src/plugins/postcss-url-parser.js
- src/utils.js
- test/__snapshots__/import-option.test.js.snap
- test/fixtures/import/import-absolute.js
- test/fixtures/import/import-conditionNames.css
- test/fixtures/import/import-conditionNames.js
- test/fixtures/import/import-server-relative-url.css
- test/fixtures/import/import-server-relative-url.js
- test/fixtures/import/issue-683.css
- test/fixtures/import/issue-683.js
- test/fixtures/import/node_modules/issue-683/index.js
- test/fixtures/import/node_modules/issue-683/package.json
- test/fixtures/import/node_modules/issue-683/test.css
- test/fixtures/import/node_modules/package-with-exports/package.json
- test/fixtures/import/node_modules/package-with-exports/style.css
- test/helpers/getModuleSource.js
- test/import-option.test.js
Fixes #683 
- respected style field from package.json
- add restrictions
No
No
> fix: respected style field from package.json

- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/composes/composes-preprocessors.css
- test/fixtures/modules/composes/composes-preprocessors.js
- test/fixtures/modules/composes/less-file.less
- test/fixtures/modules/composes/sass-file.sass
- test/fixtures/modules/composes/scss-file.scss
- test/modules-option.test.js
Add tests for composes files with extension
No
No
> test: tests for composes

- src/index.js
- test/icss.test.js
Enable icss only when enabled modules
Yes
No
> refactor: enable icss only when enabled modules

- README.md
- src/index.js
- src/options.json
- src/plugins/postcss-icss-parser.js
- src/utils.js
- test/__snapshots__/esModule-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/esModule-option.test.js
- test/fixtures/es-module/named/base/index.css
- test/fixtures/es-module/named/base/index.js
- test/fixtures/es-module/named/broken/index.css
- test/fixtures/es-module/named/broken/index.js
- test/fixtures/es-module/named/nested/index.css
- test/fixtures/es-module/named/nested/index.js
- test/fixtures/es-module/named/template/index.css
- test/fixtures/es-module/named/template/index.js
- test/fixtures/es-module/named/template/template.js
- test/fixtures/simple.css
- test/validate-options.test.js
esModule export named
Fixes #1029 
No
No
> feat: esModule  export named

- src/index.js
- src/plugins/postcss-import-parser.js
- src/plugins/postcss-url-parser.js
- test/__snapshots__/import-option.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/fixtures/import/import-order.css
- test/fixtures/import/import-order.js
- test/fixtures/import/node_modules/test/package.json
- test/fixtures/import/node_modules/test/test.css
- test/helpers/getCompiler.js
- test/helpers/preLoader.js
- test/import-option.test.js
- test/loader.test.js
- test/runtime/__snapshots__/api.test.js.snap
- test/runtime/api.test.js
> test: code coverange

- README.md
- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/modules-option.test.js
BREAKING CHANGE: the `modules.auto` option is `true` by default
Set the `auto` option to `true` value by default, better 0CJS
Yes
No
> refactor: default value `modules.auto` is true

- test/__snapshots__/import-option.test.js.snap
- test/__snapshots__/modules-option.test.js.snap
- test/__snapshots__/url-option.test.js.snap
- test/fixtures/modules/unresolved/source.css
- test/import-option.test.js
- test/modules-option.test.js
- test/url-option.test.js
> test: unresolved

- README.md
- src/options.json
- test/__snapshots__/validate-options.test.js.snap
> refactor: improve schema options

- README.md
- src/plugins/postcss-import-parser.js
- src/utils.js
- test/import-option.test.js
BREAKING CHANGE: function arguments of the `import` option were changed, it is now `funciton(url, media, resourcePath) {}`
For DX
Yes
No
> refactor: change function arguments of the `import` option

- CHANGELOG.md
Found a typo in the changelog
None
Change `funciton` to `function` in CHANGELOG.md
> Typofix in Changelog

- README.md
- src/index.js
- src/options.json
- src/utils.js
- test/__snapshots__/validate-options.test.js.snap
- test/icss.test.js
- test/validate-options.test.js
#1134 more broadly enabling other loaders to handle CSS Modules
> feat: add `icss` option

- README.md
See https://github.com/webpack-contrib/css-loader/issues/1161
added two examples for
* only icss, no modules
* both only icss, no modules and modules, sharing variables with both modules as well as JavaScript
> docs: example of icss only and mixed

- src/utils.js
- test/__snapshots__/sourceMap-option.test.js.snap
- test/sourceMap-option.test.js
> refactor: improve sources handling in source maps

- src/options.json
- src/utils.js
- test/__snapshots__/importLoaders-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/importLoaders-option.test.js
- test/validate-options.test.js
> feat: the `importLoaders` can be `string`

- test/__snapshots__/sourceMap-option.test.js.snap
- test/sourceMap-option.test.js
> test: source map

- src/options.json
- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/modules-option.test.js
- test/validate-options.test.js
> Remove icss option

- README.md
- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/issue-1191/issue-1191-custom.css
- test/fixtures/modules/issue-1191/issue-1191.css
- test/fixtures/modules/issue-1191/issue-1191.js
- test/modules-option.test.js
With the release of the 4.x version of the css-loader, the behavior that allowed a `getLocalIdent` function to return a falsy value to fallback to the default `getLocalIdent` function was lost. That original behavior was introduced in [this pull request](https://github.com/webpack-contrib/css-loader/pull/963).
This PR reintroduces that behavior, but instead requires the function to return `null` or `undefined`.
n/a
> feat: add fallback if custom getLocalIdent returns null

- src/index.js
- test/loader.test.js
Enable `hideNothingWarning` postcss option by default, to disable console.warn when plugins are missing
`hideNothingWarning` option available in `poscss@8`
No
No
> Refactor - enable hideNothingWarning option by default

- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/issue-966/issue-966.css
- test/fixtures/modules/issue-966/issue-966.js
- test/modules-option.test.js
Fixes #966 
Yes. `.` is replaced in classname
No
> Fix escape getLocalIdent

- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/modules-option.test.js
Refactor emoji deprecate
No
No
> Refactor emoji deprecate

- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/issue-1223/@foo/bar/index.module.css
- test/fixtures/modules/issue-1223/issue-1223.js
- test/modules-option.test.js
> test: `@` character

- README.md
- package.json
- test/fixtures/url/url.css
- test/url-option.test.js
update docs to using `asset` modules
No
Need provide example how use inline loaders (putted in TODO)
> docs: asset modules

- package-lock.json
- package.json
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/base64-loader/index.js
- test/fixtures/index-loader-syntax.js
- test/sourceMap-option.test.js
fixes #1273
No
/cc @jquense fixed, please look
> fix: the `auto` option for inline module syntax

- src/utils.js
fixes #1280
No
Ideally should be fixed on `thread-loader` side, but in long term multiple threading will be part of core, so fix is good right now
> fix: crash with thread-loader

- src/plugins/postcss-import-parser.js
- src/plugins/postcss-url-parser.js
Fixes https://github.com/webpack-contrib/css-loader/issues/1236.
None
My apologies for the issue lingering open. Apparently I must've cleared all my notifications and missed your response. I don't believe anything like the schema needs updating (async functions are instance of Function) so the change is pretty small.
> Support asyncronous functions in `config.url` and `config.import`.

- src/utils.js
- test/fixtures/url/url.css
> fix: do not crash on unescaped svg data uri

- src/plugins/postcss-import-parser.js
- src/plugins/postcss-url-parser.js
- src/utils.js
> perf: improve

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/import-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/import-option.test.js
- test/url-option.test.js
- test/validate-options.test.js
Reducing the number of options, bringing them to a single view
- Type `function` for `url` options replaced by an `object` with a `filter` key
- Type `function` for `import` options replaced by an `object` with a `filter` key
No
> refactor: `url` and `import` option

- package-lock.json
- package.json
- src/utils.js
- test/__snapshots__/camelCase.test.js.snap
- test/camelCase.test.js
reduce deps
removed `camelCase` package from dependencies
No
No
> refactor: removed `camelCase` package from dependencies

- CHANGELOG.md
- README.md
I was very confused by the phrasing in the section about the `url` option, especially when upgrading from an older version of `css-loader` which allowed absolute paths starting from the `publicPath`. This I _think_ clarifies it, but since I was confused, I'm still not entirely sure if this understanding is correct. Please let me know if I'm wrong about how it works!
> Clarify behavior of URL option

- README.md
recommended use case added
No
No
> docs: recommend

- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
fixed compatibility with named export and es5
No
No
> fix: compatibility with named export and es5

- src/index.js
- src/utils.js
- test/__snapshots__/esModule-option.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/modules-option.test.js.snap
> fix: locals export

- README.md
- src/options.json
- test/__snapshots__/validate-options.test.js.snap
Updated css modules info
No
No
> docs: update

- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/mode/entry.css
- test/helpers/getCompiler.js
- test/modules-option.test.js
> Issue 1307 test

- README.md
- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/ComponentName/index.js
- test/fixtures/modules/ComponentName/index.modules.css
- test/modules-option.test.js
added `[folder]` + refactor
No
fixes #1372 fixes #1371
> Feat folder placeholder

- test/loader.test.js
Assets enabled by default - https://github.com/webpack/webpack/pull/11413
No need in experiments 
Fix CI, option enabled by default now
no
> fix: remove asset experiment, fix test

- src/utils.js
- test/helpers/readAsset.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
None
> Replace deprecated String.prototype.substr()

- README.md
The current documentation suggests that `url` can be set to an object with `url` as a property, whereas this should be `filter`
> docs: fix typo in url object syntax

- README.md
Provide an example for a common scenario (https://github.com/webpack/webpack/issues/15499).
I'm assuming this updates the docs at https://webpack.js.org/loaders/css-loader/#object-1. If this is not the case, please point me in the right direction.
> Added extra example for url.filter for a common scenario

- .github/workflows/cancel.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows.
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes.
Here is an example of the permissions in one of the workflow runs:
https://github.com/webpack-contrib/css-loader/runs/8160728230?check_suite_focus=true#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflow:
- cancel.yml
The following workflow file already has the least privileged token permission set:
- nodejs.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- GitHub recommends defining minimum GITHUB_TOKEN …
> ci: add minimum GitHub token permissions for workflows

- test/__snapshots__/import-option.test.js.snap
- test/fixtures/import/dark.css
- test/fixtures/import/list-of-media-queries.css
- test/fixtures/import/list-of-media-queries.js
- test/import-option.test.js
fixes https://github.com/webpack-contrib/css-loader/issues/1503 (just test)
> test: more

- README.md
- src/index.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/basic-built-in-css-support.js
- test/loader.test.js
For better DX
No
part of https://github.com/webpack/webpack/issues/17223, need to solve it for `mini-css-extract-plugin` and `style-loader` too
> fix: output warning when built-in CSS support enabled

- package-lock.json
- package.json
- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/tests-cases/keyframes-and-animation/source.css
fixes https://github.com/webpack-contrib/css-loader/issues/1432
No
No
> Fix bugs in css modules

- src/utils.js
use `cause` for original errors and warnings
No
No
> fix: use `cause` for original errors and warnings

- package-lock.json
- package.json
Updated postcss dependency, that includes the fix for CVE-2023-44270
Fix vulnerability https://github.com/advisories/GHSA-7fh5-64p2-3v2j
> chore: update package dependencies

- package-lock.json
- package.json
- src/utils.js
I would like the ability to only transform class names and not transform id. This is because keeping the original id is useful for anchoring (href="#section1") as well as code that rely on finding elements by id (automated tests, analytics, vanilla js, etc).
https://github.com/webpack-contrib/css-loader/issues/1540
N/A
Updated postcss-modules-scope dependency with latest which passes the node object to generateExportEntry. The node object has a "type" property that can be used to determine if the node is an id or class.
> Updated generateExportEntry to expose node details

- CHANGELOG.md
- README.md
- src/utils.js
- test/__snapshots__/exportType.test.js.snap
- test/__snapshots__/modules-option.test.js.snap
- test/url-option.test.js
I noticed that in the changelogs and in some other places, `esModules` is used, but the doc and the code uses `esModule`. So I renamed everything to match the code
Shouldn't contain any
We may want to rewrite the releases in GitHub too
> chore(typo): rename esModules -> esModule to match the code

- src/index.js
- test/__snapshots__/loader.test.js.snap
https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1067
No
https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1067
> fix: css experiment detection

- test/modules-option.test.js
test for https://github.com/webpack-contrib/css-loader/issues/1540
No
No
> test: getLocalIdent and node type

- CHANGELOG.md
- README.md
- src/utils.js
- test/__snapshots__/modules-option.test.js.snap
- test/exportType.test.js
- test/fixtures/modules/namedExport/exportsAs/exportsAs.css
- test/fixtures/modules/namedExport/exportsAs/index.js
- test/modules-option.test.js
The limitation of only allowing `camelCase` named exports fails to take into account the full capabilities of module exports. In fact, you can export any name you want with `export { local as "string literal" }`.
This removes the limitation and allows you to set
`exportLocalsConvention` back to `asIs` when using the `namedExports` option.
Relevant syntax documentation can be found here:
https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#syntax
This allows you to set `exportLocalsConvention` back to any valid option when `namedExports` is set (which changes the option to "camelCase", and restricts you from changing it). Exported names do not have the same restrictions as source identifiers [since tc39/ecma262#2154] so there is no need …
> feat: support named exports with any characters

- package-lock.json
- package.json
- test/__snapshots__/modules-option.test.js.snap
test for https://github.com/webpack-contrib/css-loader/issues/1579
No
No
> test: for @scope

- README.md
- package-lock.json
- package.json
- test/__snapshots__/modules-option.test.js.snap
- test/fixtures/modules/composes/alias-1.css
- test/fixtures/modules/composes/multiple.css
- test/fixtures/modules/composes/multiple.js
- test/modules-option.test.js
fixes https://github.com/webpack-contrib/css-loader/issues/1564
No
No
> feat: supports multiple composes

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/modules-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/fixtures/modules/getJSON/composeSource.css
- test/fixtures/modules/getJSON/source.css
- test/fixtures/modules/getJSON/source.js
- test/helpers/normalizeErrors.js
- test/modules-option.test.js
- test/url-option.test.js
- test/validate-options.test.js
This changeset adds a `getJSON` option to output CSS modules mappings to JSON.  This value can be a boolean or a function, and it employs similar logic to [postcss-modules#getJSON](https://github.com/madyankin/postcss-modules?tab=readme-ov-file#saving-exported-classes) as a function.  This is particularly useful for SSR/SSG/templating languages when CSS modules mappings need to be present at build time.
Addresses [#988](https://github.com/webpack-contrib/css-loader/issues/988).
N/A
> feat: add getJSON option to output CSS modules mapping

- CHANGELOG.md
- README.md
fixes https://github.com/webpack-contrib/css-loader/issues/1585
No
No
> docs: update migration guide

- README.md
- src/index.js
- test/__snapshots__/modules-option.test.js.snap
- test/helpers/get-json.js
- test/modules-option.test.js
Added a real test + refactor code + make paths relative
No
No
> docs: update logic

- src/index.js
- src/utils.js
> refactor: use `environment` to get `templateLiteral` value

- src/utils.js
> fix: use official `createHash` for hashes
